### PR TITLE
docs: standardizing contrib guidelines

### PR DESCRIPTION
**Pull request by Thoughtscript**
OK, this is for real this time :)

I'm standardizing some of the coding and contribution guidelines here before turning to project-specific documentation! Also improving some of the setup guidelines to help streamline on-boarding, etc.

### CODE REVIEW

**Comment by epiqueras** [comment]
Hi @Thoughtscript,
I actually just finished writing a Gitbook with our contribution guidelines. Feel free to submit a PR against that tomorrow when we publish it, if you think we missed something.

**Comment by n1c01a5** [comment]
@Thoughtscript but I noted your contribution. Tnx

**Comment by n1c01a5** [comment]
@epiqueras in waiting the gitbook this contribution makes sense

**Comment by Thoughtscript** [comment]
@epiqueras - @n1c01a5 - Rock on. Will incorporate any changes into GitBook.

**Comment by epiqueras** [comment]
Gitbook is up now.

**Pull request closed without merging**
